name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'

    - name: Install dependencies
      run: julia -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests
      run: julia --project --code-coverage=all -e 'using Pkg; Pkg.test()'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        verbose: true

