name: Documentation

on:
  push:
    branches:
      - main  # or "master" if that’s your default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
        
      - name: Build and deploy docs
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
